# Generated by Django 2.2.7 on 2019-12-16 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='car_choose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='media/car_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Giverent_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/images')),
                ('seat_capacity', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User_rent_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField()),
                ('rent_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('upload_lic', models.ImageField(upload_to='media/license')),
            ],
        ),
        migrations.CreateModel(
            name='sell_car_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('engine_capacity', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('seat_capacity', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='pictures/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
